FROM apache/airflow:2.8.4-python3.10

USER root

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install dbt + GCP libs as airflow user
USER airflow

RUN pip install --no-cache-dir \
    dbt-core==1.9.2 \
    dbt-bigquery==1.9.2 \
    google-cloud-bigquery \
    google-cloud-storage \
    pandas \
    pyarrow \
    requests
